### PR TITLE
Simplify verbose pipeline output

### PR DESCRIPTION
**Pull request by wader**
Only show outputs instead of diffs, mostly confusing.

### CODE REVIEW

**Comment by wader** [comment]
@v1gnesh what do you think about this output? one version per row and also just show output versions per filter, i think that might be clearer

**Comment by wader** [comment]
Example output (also includes change to leave "lower" semver versions):
```
$ bump pipeline -v 'gitrefs:https://github.com/sudo-project/sudo.git|/SUDO_(1_9_.*)/$1/|/_/./|*'
Parsed pipeline: gitrefs:https://github.com/sudo-project/sudo.git|re:/SUDO_(1_9_.*)/$1/|re:/_/./|semver:*
gitrefs:https://github.com/sudo-project/sudo.git:
  HEAD:commit=64b666471a9010ad1f52533bac1e51db1d4d1882
  refs/heads/audit-server-tls-support:commit=8c8023d212fd2e2ec7991853833a0336ac591844
  refs/heads/main:commit=64b666471a9010ad1f52533bac1e51db1d4d1882
  refs/heads/sudo-1.7:commit=85173304b7286bca7696a4e44415f2527092fdba
  ...<cut>...
  refs/tags/SUDO_1_9_8p1:commit=f5f4a544b3c43a3227f71f152aa3f6c494a6cbb5
  refs/tags/SUDO_1_9_8p2:commit=48911e69122a85b78bb17126ef90d67d3a733cdc
  refs/tags/SUDO_1_9_9:commit=7e1795b7d25dcb1303695ddadc299995637ed7d6
  refs/tags/TAG:commit=a4f31cff2b43cc0e5ad6b5c19ef5dd9a64bd883c
  @ name -> name
re:/SUDO_(1_9_.*)/$1/:
  1_9_0:commit=83d1bee918147a57804de77d3e1064a4e323f47e
  1_9_1:commit=7ada70e14f9075e67ed821d0470ded470370563e
  1_9_10:commit=cc56fc18efca97326044721850466f1d5ad3df28
  1_9_11:commit=3aa7142d2933485c6199fc2e3089e19aafb72b5e
  1_9_11p1:commit=212252e4ff6aea1de771fb95e21dfa6154c07821
  1_9_11p2:commit=f55a58b5eb176cb7b7ba801ef542e0a95d5509bc
  1_9_11p3:commit=b9dab8cdad820f1914bc528e3487934c653a61a9
  1_9_12:commit=c684bf08307b3270a62f2130bafb37c36aa3c99e
  1_9_12p1:commit=7a103879a054ec428dd8ed9b4cee8077102900ec
  1_9_12p2:commit=a49b2da91c2b6d33fd75f0c718835d19470804af
  1_9_13:commit=effed9ecbb54acedcbf32d53d9ebd571498867b4
  1_9_13p1:commit=05cab83b1f5d0ff0ed60fee5ea4871c90392f5ec
  1_9_13p2:commit=dc7ad19cbaa1c442b94309f38687954ca0c1c52f
  1_9_13p3:commit=4e0de8d55325d103b9ab0e9f88aeb320ce64d6d6
  1_9_2:commit=1c5fddc04577de5261d0ae810c7ec013815e22dc
  1_9_3:commit=2c102c6ccc28739d540a0c9fa29daefb85295ad1
  1_9_3p1:commit=cfa5b999247e522a2bbd4690a79058579aaa0aa5
  1_9_4:commit=de029fc2aa5fb5c0065ecf3709c4ffcfb8ca91f4
  1_9_4p1:commit=821d31cdf72967b3e9303d126c548dbd96d775d6
  1_9_4p2:commit=be7da005fed7fd08ef74e6e359346389d09aafa9
  1_9_5:commit=10d072a320c885e2e805ef2e47fe7a2ebde68abc
  1_9_5p1:commit=8a0373679a24306a2dc57677dbc6d87d1611c8bc
  1_9_5p2:commit=0ce657ca6ded62b93c75e8cde992a210bf90fa51
  1_9_6:commit=b0842bc55c312d9f4d7f4f712c5b63fa56a8d3df
  1_9_6p1:commit=21d16d3669cc593cb47aee7a6ccbee248e7e8ee3
  1_9_7:commit=a430a955b5c1cbff290c5c93b0c64dc117f9cc95
  1_9_7p1:commit=6342b8b53a4b0e72d14bc6756aee34898d459bc4
  1_9_7p2:commit=1bea775857bb2d78e0942ddeab829b40396d05d4
  1_9_8:commit=affd3d06d6446a882df582618d5aeda6daa68eb3
  1_9_8p1:commit=f5f4a544b3c43a3227f71f152aa3f6c494a6cbb5
  1_9_8p2:commit=48911e69122a85b78bb17126ef90d67d3a733cdc
  1_9_9:commit=7e1795b7d25dcb1303695ddadc299995637ed7d6
  @ name -> name
re:/_/./:
  1.9.0:commit=83d1bee918147a57804de77d3e1064a4e323f47e
  1.9.1:commit=7ada70e14f9075e67ed821d0470ded470370563e
  1.9.10:commit=cc56fc18efca97326044721850466f1d5ad3df28
  1.9.11:commit=3aa7142d2933485c6199fc2e3089e19aafb72b5e
  1.9.11p1:commit=212252e4ff6aea1de771fb95e21dfa6154c07821
  1.9.11p2:commit=f55a58b5eb176cb7b7ba801ef542e0a95d5509bc
  1.9.11p3:commit=b9dab8cdad820f1914bc528e3487934c653a61a9
  1.9.12:commit=c684bf08307b3270a62f2130bafb37c36aa3c99e
  1.9.12p1:commit=7a103879a054ec428dd8ed9b4cee8077102900ec
  1.9.12p2:commit=a49b2da91c2b6d33fd75f0c718835d19470804af
  1.9.13:commit=effed9ecbb54acedcbf32d53d9ebd571498867b4
  1.9.13p1:commit=05cab83b1f5d0ff0ed60fee5ea4871c90392f5ec
  1.9.13p2:commit=dc7ad19cbaa1c442b94309f38687954ca0c1c52f
  1.9.13p3:commit=4e0de8d55325d103b9ab0e9f88aeb320ce64d6d6
  1.9.2:commit=1c5fddc04577de5261d0ae810c7ec013815e22dc
  1.9.3:commit=2c102c6ccc28739d540a0c9fa29daefb85295ad1
  1.9.3p1:commit=cfa5b999247e522a2bbd4690a79058579aaa0aa5
  1.9.4:commit=de029fc2aa5fb5c0065ecf3709c4ffcfb8ca91f4
  1.9.4p1:commit=821d31cdf72967b3e9303d126c548dbd96d775d6
  1.9.4p2:commit=be7da005fed7fd08ef74e6e359346389d09aafa9
  1.9.5:commit=10d072a320c885e2e805ef2e47fe7a2ebde68abc
  1.9.5p1:commit=8a0373679a24306a2dc57677dbc6d87d1611c8bc
  1.9.5p2:commit=0ce657ca6ded62b93c75e8cde992a210bf90fa51
  1.9.6:commit=b0842bc55c312d9f4d7f4f712c5b63fa56a8d3df
  1.9.6p1:commit=21d16d3669cc593cb47aee7a6ccbee248e7e8ee3
  1.9.7:commit=a430a955b5c1cbff290c5c93b0c64dc117f9cc95
  1.9.7p1:commit=6342b8b53a4b0e72d14bc6756aee34898d459bc4
  1.9.7p2:commit=1bea775857bb2d78e0942ddeab829b40396d05d4
  1.9.8:commit=affd3d06d6446a882df582618d5aeda6daa68eb3
  1.9.8p1:commit=f5f4a544b3c43a3227f71f152aa3f6c494a6cbb5
  1.9.8p2:commit=48911e69122a85b78bb17126ef90d67d3a733cdc
  1.9.9:commit=7e1795b7d25dcb1303695ddadc299995637ed7d6
  @ name -> name
semver:*:
  1.9.13:commit=effed9ecbb54acedcbf32d53d9ebd571498867b4
  1.9.12:commit=c684bf08307b3270a62f2130bafb37c36aa3c99e
  1.9.11:commit=3aa7142d2933485c6199fc2e3089e19aafb72b5e
  1.9.10:commit=cc56fc18efca97326044721850466f1d5ad3df28
  1.9.9:commit=7e1795b7d25dcb1303695ddadc299995637ed7d6
  1.9.8:commit=affd3d06d6446a882df582618d5aeda6daa68eb3
  1.9.7:commit=a430a955b5c1cbff290c5c93b0c64dc117f9cc95
  1.9.6:commit=b0842bc55c312d9f4d7f4f712c5b63fa56a8d3df
  1.9.5:commit=10d072a320c885e2e805ef2e47fe7a2ebde68abc
  1.9.4:commit=de029fc2aa5fb5c0065ecf3709c4ffcfb8ca91f4
  1.9.3:commit=2c102c6ccc28739d540a0c9fa29daefb85295ad1
  1.9.2:commit=1c5fddc04577de5261d0ae810c7ec013815e22dc
  1.9.1:commit=7ada70e14f9075e67ed821d0470ded470370563e
  1.9.0:commit=83d1bee918147a57804de77d3e1064a4e323f47e
  @ name -> name
  value 1.9.13
1.9.13
```

**Comment by v1gnesh** [comment]
Perfect!
Without the trailing `|*`, will it return 1.9.13p3 instead?
Also, will it still be relevant, if just the first 6 from commit ID is shown?

`  1.9.0:commit=83d1bee918147a57804de77d3e1064a4e323f47e`
vs
`  1.9.0:commit=83d1be`

6 or 8, whatever the norm is..

**Comment by wader** [comment]
> Perfect! Without the trailing `|*`, will it return 1.9.13p3 instead? 

Not in this case, unless the tags happen to be that order. The pipeline was mostly to show off -v :) but once we have version sort it should work, even if versions have "_" instead of "." as separator. Then guess it depend what your going to use the string for if you want to replace with dots or not.

> Also, will it still be relevant, if just the first 6 from commit ID is shown?
> 
> ` 1.9.0:commit=83d1bee918147a57804de77d3e1064a4e323f47e` vs ` 1.9.0:commit=83d1be`
> 
> 6 or 8, whatever the norm is..

I think i would probably want to add a substring filter or you could possibly use the regex filter to do that already. The commit hash is what the git repo responded with so think i would like to leave that as raw as possible and then let the user use some filter to transform it.  We could possibly add a "short_commit" or something to allow `"git://...|...|@short_commit"` i guess? eithe that or a filter, regex to do it feels a bit hacky.

**Comment by v1gnesh** [comment]
The output is pretty neat now, so no worries.
And perhaps move the original -v output to -vv ?
Sometimes, it _is_ useful to see bits of HTML, to figure out the exact regex incantation.

>  We could possibly add a "short_commit" or something to allow "git://...|...|@short_commit" i guess? eithe that or a filter, regex to do it feels a bit hacky.

Nah, the existing one should be fine, as it fits on the screen anyway.

Thank you for helping with this!

**Pull request merged**
